# Generated by Django 4.2.2 on 2026-03-25 01:49

import json
from pathlib import Path
from django.db import migrations
from django.utils.dateparse import parse_datetime


def import_blog_data(apps, schema_editor):
    Author = apps.get_model("blog", "Author")
    Post = apps.get_model("blog", "Post")
    base_dir = Path(__file__).resolve().parent.parent.parent
    authors_folder = base_dir / "data" / "authors"
    for file_path in authors_folder.glob("*.json"):
        with file_path.open("r", encoding="utf-8") as f:
            item = json.load(f)
            Author.objects.update_or_create(
                id=item["id"],
                defaults={
                    "full_name": item["full_name"],
                    "created_at": parse_datetime(item["created_at"]),
                    "modified_at": parse_datetime(item["modified_at"]),
                },
            )
    posts_folder = base_dir / "data" / "posts"
    for file_path in posts_folder.glob("*.json"):
        with file_path.open("r", encoding="utf-8") as f:
            item = json.load(f)
            Post.objects.update_or_create(
                id=item["id"],
                defaults={
                    "title": item["title"],
                    "body": item["body"],
                    "created_at": parse_datetime(item["created_at"]),
                    "modified_at": parse_datetime(item["modified_at"]),
                    "published_at": parse_datetime(item["published_at"])
                    if item.get("published_at")
                    else None,
                    "author_id": item["author"],
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(import_blog_data, migrations.RunPython.noop),
    ]
